apiVersion: v1
kind: ConfigMap
metadata:
  name: clinical-init-sql
data:
  init.sql: |
    CREATE USER 'root'@'%' IDENTIFIED BY 'admintsd';
    GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
    FLUSH PRIVILEGES;
