apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinical-manager
  template:
    metadata:
      labels:
        app: clinical-manager
    spec:
      containers:
        - name: clinical-manager
          image: clinical-manager:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3301
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: clinical-config
                  key: PORT
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: clinical-config
                  key: DB_HOST
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: clinical-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: clinical-config
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: clinical-config
                  key: DB_NAME
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: clinical-config
                  key: DB_PORT